name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Cambia "main" por la rama que uses

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push convert service image
      run: |
        sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/convertidor-convert:latest ./convert_service
        sudo docker push ${{ secrets.DOCKER_USERNAME }}/convertidor-convert:latest

    - name: Build and push rates service image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/convertidor-rates:latest ./rates_service
        docker push ${{ secrets.DOCKER_USERNAME }}/convertidor-rates:latest