name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Cambia "main" por la rama que uses

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for rates_service
      uses: docker/build-push-action@v3
      with:
        context: ./rates_service
        file: ./rates_service/dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/convertidor-rates-service:latest

    - name: Build and push Docker image for convert_service
      uses: docker/build-push-action@v3
      with:
        context: ./convert_service
        file: ./convert_service/dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/convertidor-convert-service:latest