name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Cambia "main" por la rama que uses

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/convertidor-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/convertidor-frontend:latest

    - name: Build and push convert service image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/convertidor-convert-service:latest ./convert-service
        docker push ${{ secrets.DOCKER_USERNAME }}/convertidor-convert-service:latest

    - name: Build and push rates service image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/convertidor-rates-service:latest ./rates-service
        docker push ${{ secrets.DOCKER_USERNAME }}/convertidor-rates-service:latest